apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: backend
spec:
  selector:
    app: nexus
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP

# nexus Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus-container
        image: ashutoshrajput81/nexus:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        

