# @author - Ankit Khatri
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service
  name: zookeeper-service
  namespace: kafka-namespace
spec:
  selector:
    app: zookeeper
  ports:
  - protocol: TCP
    name: zookeeper-port
    port: 2181
    targetPort: 2181
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kafka-namespace
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181