apiVersion: v1
kind: Service
metadata:
  name: userinfo-service
  namespace: backend
spec:
  selector:
    app: userinfo
  ports:
  - protocol: TCP
    port: 8282
    targetPort: 8282
  type: LoadBalancer

# userinfo Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userinfo-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userinfo
  template:
    metadata:
      labels:
        app: userinfo
    spec:
      containers:
      - name: userinfo-container
        image: ashutoshrajput81/userinfo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8282
        

